- name: Deploy RKE2
  hosts: k8s_cluster
  become: yes
  vars_files:
    - ../host_vars/main.yml
  vars:
    rke2_airgap_mode: true
    rke2_airgap_implementation: 'download'
    rke2_cni: 'cilium'
    rke2_ha_mode: true
    rke2_api_ip : 192.168.1.50
    rke2_download_kubeconf: true
    rke2_version: 'v1.31.6+rke2r1'
    rke2_disable_cloud_controller: true
    rke2_cluster_domain: 'cluster.local'
    rke2_agent_token: 'O+HkGqhGqCukrMS5'
    rke2_token: 'O+HkGqhGqCukrMS5'
    rke2_cis_profile: "cis"
    rke2_disable:
      - 'rke2-ingress-nginx'
      - 'rke2-canal'
    disable_kube_proxy: true
    rke2_kube_apiserver_args:
      - '--default-not-ready-toleration-seconds=30'
      - '--default-unreachable-toleration-seconds=30'
    rke2_kube_controller_manager_arg:
      - '--node-monitor-period=4s'
      - '--allocate-node-cidrs=true'
      - '--bind-address=0.0.0.0'
    rke2_kubelet_arg:
      - '--node-status-update-frequency=4s'
      - '--max-pods=100'
    rke2_server_node_taints:
      - 'CriticalAddonsOnly=true:NoExecute'
      - 'node-role.kubernetes.io/control-plane=true:NoSchedule'
      - 'node-role.kubernetes.io/etcd=true:NoExecute'
    rke2_artifact:
      - 'sha256sum-{{ rke2_architecture }}.txt'
      - 'rke2.linux-{{ rke2_architecture }}.tar.gz'
      - 'rke2-images.linux-{{ rke2_architecture }}.tar.zst'
      - 'rke2-images-cilium.linux-{{ rke2_architecture }}.tar.zst'
    rke2_kube_scheduler_arg:
      - '--bind-address=0.0.0.0'
  roles:
     - rke2